### ISSUE TITLE
NoClassDefFoundError ParquetDecodingException in Loading csv 

### ISSUE THREAD

**Issue by Agent1101** [spark-notebook/spark-notebook#981]
I built with `sbt -D"spark.version"="2.3.1" -D"hadoop.version"="2.7.7" -D"jets3t.version"="0.9.4" -Dmesos.version="1.7.1" -Dwith.hive=true -Dwith.parquet=true -Dwith.mesos=true` and when loading csv exception raises!

> _org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver):_ **java.lang.NoClassDefFoundError: org/apache/parquet/io/ParquetDecodingException**
	_at org.apache.spark.sql.execution.datasources.FileScanRDD.compute(FileScanRDD.scala:75)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)_

* it happens in spark 2.3.1 and above but works fine with spark 2.3.0 and below!
* it happens in windows but no problem in linux (tested on ubuntu and works fine with all spark versions)
* I built in windows 7 x64
* my code:
> import org.apache.spark.sql._
import org.apache.spark.sql.functions._ 
val spark = SparkSession.builder.master("local").appName("Spark CSV Reader").getOrCreate;
val df = spark.read.format("csv").option("header", "false").option("delimiter","\t").option("inferSchema","true").load("snbbooks/sample_few.txt")

as I said exception happens in spark >= v2.3.1 in windows!
